name: Deploy Workflow Service

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest on server repo
        run: |
          cd /snap/snapd-desktop-integration/315/badminton-dev/Workflow-service
          git fetch origin
          git reset --hard origin/develop

      - name: Install + build + reload
        run: |
          cd /snap/snapd-desktop-integration/315/badminton-dev/Workflow-service
          npm ci
          npm run build
          pm2 reload workflow-service --update-env
          pm2 save
