name: Deploy Workflow-service (DEV/PROD)

on:
  push:
    tags:
      - "dev-v*"
      - "prod-v*"

jobs:
  deploy_dev:
    if: startsWith(github.ref_name, 'dev-v')
    runs-on: [self-hosted, dev]
    steps:
      - name: Deploy DEV by tag
        run: |
          set -e
          cd ~/snap/snapd-desktop-integration/315/badminton-dev/workflow-service
          git fetch origin --tags
          git checkout "${GITHUB_REF_NAME}"

          npm ci
          npm run prisma:generate
          npm run build
          pm2 restart workflow-service --update-env || pm2 start dist/workflow-service/src/main.js --name workflow-service
          pm2 save

  deploy_prod:
    if: startsWith(github.ref_name, 'prod-v')
    runs-on: [self-hosted, prod]
    steps:
      - name: Deploy PROD by tag
        run: |
          set -e
          cd ~/snap/snapd-desktop-integration/315/badminton-prod/workflow-service
          git fetch origin --tags
          git checkout "${GITHUB_REF_NAME}"

          npm ci
          npm run prisma:generate
          npm run build
          pm2 restart workflow-service --update-env || pm2 start dist/workflow-service/src/main.js --name workflow-service
          pm2 save
